baseURL = "https://nathankuik.com/"
languageCode = "en-us"
title = "Nathan Kuik"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Nathan Kuik"
    description = "Nathan Kuik's personal website"
    keywords = "blog,developer,personal"
    info = "Software Developer"

    hideCredits = false
    hideCopyright = false

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/nkuik/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/nathankuik/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/nathankuik/"
[[params.social]]
    name = "Email"
    weight = 4
    url = "mailto:nathan@nathankuik.com"


[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
