name: build-site

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: install submodule
      run: |
        git submodule update --init

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        target: docs

    - name: push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Build site for $GITHUB_HEAD_REF" || true
        git push -f origin $GITHUB_HEAD_REF || true

    - name: run server
      run: |
        docker run --rm -itd \
          -v $(pwd):/src \
          -p 1313:1313 \
          klakegg/hugo:0.80.0 \
          server

    # steps:
    #   - name: Checkout GitHub Action Repo
    #     uses: actions/checkout@v2
    #     with:
    #       repository: nkuik/portfolio 
    #       ref: ${{ github.event.pull_request.head.ref }}
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #   - name: Build site 
    #     uses: ./actions/build-site
    #     with:
    #       github_user: github
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
