name: build-site

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: build site
      uses: klakegg/actions-hugo@1.0.0
      with:
        target: docs

    - name: run lighthouse ci 
      uses: treosh/lighthouse-ci-action@v3
      with:
        configPath: "./lighthouserc.json"
        temporaryPublicStorage: true
        uploadArtifacts: true

    - name: push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Build site for $GITHUB_HEAD_REF" || true
        git push -f origin $GITHUB_HEAD_REF || true
