name: build-site

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install submodule
      run: |
        git submodule update --init
        export

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0

    - name: push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add docs
        git commit -m "Build site for $GITHUB_HEAD_REF"
        git push -f origin $GITHUB_HEAD_REF

    # steps:
    #   - name: Checkout GitHub Action Repo
    #     uses: actions/checkout@v2
    #     with:
    #       repository: nkuik/portfolio 
    #       ref: ${{ github.event.pull_request.head.ref }}
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #   - name: Build site 
    #     uses: ./actions/build-site
    #     with:
    #       github_user: github
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
