name: Build and Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@12.6.1
        with:
          configPath: "./lighthouserc.json"
          temporaryPublicStorage: true
          uploadArtifacts: true
