name: build-site

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: install submodule and checkout PR branch
      run: |
        ls
        git diff
        git submodule update --init
        # git checkout $GITHUB_HEAD_REF
        rm -r docs
        ls
        git diff

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        target: docs

    - name: push changes
      run: |
        ls
        git diff
        git config --global user.name "github-actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Build site for $GITHUB_HEAD_REF"
        git push -f origin $GITHUB_HEAD_REF

    # steps:
    #   - name: Checkout GitHub Action Repo
    #     uses: actions/checkout@v2
    #     with:
    #       repository: nkuik/portfolio 
    #       ref: ${{ github.event.pull_request.head.ref }}
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #   - name: Build site 
    #     uses: ./actions/build-site
    #     with:
    #       github_user: github
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
